//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIServiceTemplate1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoPGP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificadoPGP()
        {
            this.ClientePGP = new HashSet<ClientePGP>();
        }
    
        public long Id { get; set; }
        public string CertificadoPublico { get; set; }
        public string CertificadoPrivado { get; set; }
        public string Clave { get; set; }
        public string UbicacionCertificadoPublico { get; set; }
        public string UbicacionCertificadoPrivado { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaCaducidad { get; set; }
        public string Estado { get; set; }
        public Nullable<int> LongitudCifrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientePGP> ClientePGP { get; set; }
    }
}
