//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIServiceTemplate1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientePGP
    {
        public long Id { get; set; }
        public long IdCliente { get; set; }
        public long IdCertificadoPGP { get; set; }
        public string CorreoNotificacion { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public string ClaveEnviada { get; set; }
    
        public virtual CertificadoPGP CertificadoPGP { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
